src/test/java/it/pagopa/pn/bff/rest/AddressesControllerTest.java
Replaced MonoComparator with MonoMatcher
=> chore: update MonoComparator

docs/openapi/common-refs.yaml, src/main/java/it/pagopa/pn/bff/rest/AddressesController.java
=> chore: make cxRoleAuthFleet optional

docs/openapi/aws/api-bff-WEB-aws.yaml, docs/openapi/digital-addresses-schemas/digital-addresses.yaml, src/test/java/it/pagopa/pn/bff/mappers/addresses/AddressesMapperTest.java
Remove codeValid and recipientId and capitalize BffAddressType
=> chore: remove codeValid and recipientId and capitalize BffAddressType

codegen/config.json, docs/openapi/api-external-pn-bff-pa-info.yaml, docs/openapi/api-external-pn-bff-payments.yaml, docs/openapi/api-external-pn-bff-recipient-info.yaml, docs/openapi/api-internal-pn-bff-info-recipient.yaml, docs/openapi/api-internal-pn-bff-pa-info.yaml, docs/openapi/api-internal-pn-bff-payments.yaml, docs/openapi/api-internal-pn-bff-recipient-info.yaml, docs/openapi/aws/api-bff-WEB-aws.yaml, docs/openapi/info-recipient-schemas/info-recipient.yaml, pom.xml, src/main/java/it/pagopa/pn/bff/config/MsClientConfig.java, src/main/java/it/pagopa/pn/bff/mappers/inforecipient/GroupsMapper.java, src/main/java/it/pagopa/pn/bff/pnclient/externalregistries/PnExternalRegistriesClientImpl.java, src/main/java/it/pagopa/pn/bff/rest/InfoPaController.java, src/main/java/it/pagopa/pn/bff/rest/InfoRecipientController.java, src/main/java/it/pagopa/pn/bff/service/ApiKeysPaService.java, src/main/java/it/pagopa/pn/bff/service/InfoPaService.java, src/main/java/it/pagopa/pn/bff/service/InfoRecipientService.java, src/test/java/it/pagopa/pn/bff/mappers/inforecipient/GroupsMapperTest.java, src/test/java/it/pagopa/pn/bff/mocks/RecipientInfoMock.java, src/test/java/it/pagopa/pn/bff/pnclient/externalregistries/PnExternalRegistriesClientImplTest.java, src/test/java/it/pagopa/pn/bff/pnclient/externalregistries/PnExternalRegistriesClientImplTestIT.java, src/test/java/it/pagopa/pn/bff/rest/InfoPaControllerTest.java, src/test/java/it/pagopa/pn/bff/rest/InfoRecipientControllerTest.java, src/test/java/it/pagopa/pn/bff/service/ApiKeysPaServiceTest.java, src/test/java/it/pagopa/pn/bff/service/InfoPaServiceTest.java, src/test/java/it/pagopa/pn/bff/service/InfoRecipientServiceTest.java, src/test/java/it/pagopa/pn/bff/utils/PnBffRestConstants.java
This PR introduces a proxy for the list of groups in PG.
=> PN-10956-be-api-lista-gruppi-pg

scripts/aws/cfn/storage.yml
=> [PN-11337] Fixed RaddStoreRegistryLambdaName and DataIndexerLambdaName in storage output

scripts/aws/cfn/microservice.yml, scripts/aws/cfn/storage.yml
=> [PN-11337]  Fixed SubnetsIds type in microservice.yml

functions/raddStoreRegistryLambda/package-lock.json, functions/raddStoreRegistryLambda/package.json
=> PN-11337: fix required module

functions/raddStoreRegistryLambda/index.js, functions/raddStoreRegistryLambda/src/app/StoreLocatorCsvEntity.js, functions/raddStoreRegistryLambda/src/app/csvUtils.js, functions/raddStoreRegistryLambda/src/app/eventHandler.js, functions/raddStoreRegistryLambda/src/test/csvUtils.test.js, functions/raddStoreRegistryLambda/src/test/eventHandler.test.js, scripts/aws/cfn/microservice.yml
=> Fixed Lambda permissions

functions/raddStoreRegistryLambda/src/app/eventHandler.js
=> fixed header csv delimiter

functions/raddStoreRegistryLambda/src/app/csvUtils.js, functions/raddStoreRegistryLambda/src/app/eventHandler.js, functions/raddStoreRegistryLambda/src/test/csvUtils.test.js
=> fix: removed last empty row

docs/openapi/aws/api-bff-WEB-aws.yaml, docs/openapi/digital-addresses-schemas/digital-addresses.yaml, scripts/aws/cfn/microservice-dev-cfg.json
exspose additional codeValid field
=> exspose additional codeValid field

docs/openapi/apikeys-schemas/api-keys.yaml, docs/openapi/aws/api-bff-WEB-aws.yaml, docs/openapi/common-refs.yaml, docs/openapi/digital-addresses-schemas/digital-addresses.yaml, docs/openapi/info-pa-schemas/info-pa.yaml, docs/openapi/info-recipient-schemas/info-recipient.yaml, docs/openapi/notification-schemas/notification.yaml, docs/openapi/notification-schemas/parameters-notification.yaml, docs/openapi/payments-schemas/payments.yaml, docs/openapi/tos-privacy-schemas/tos-privacy.yaml, pom.xml, src/main/java/it/pagopa/pn/bff/mappers/CxTypeMapper.java
Updated micro services tags to last releases versions
- Updated versions in the pom file
- Updated versions into the api configuration file
- Regenerated external files
Run clean install and check that everything goes well
=> updated micro services tags - pn-11523

pom.xml
=> [1.1.0] Modifica versione nel pom.xml

functions/senderDashboardDataIndexer/src/app/checkLastDate.js, functions/senderDashboardDataIndexer/src/app/config.js, functions/senderDashboardDataIndexer/src/app/eventHandler.js, functions/senderDashboardDataIndexer/src/test/checkLastDate.test.js, functions/senderDashboardDataIndexer/src/test/eventHandler.test.js, scripts/aws/cfn/microservice-dev-cfg.json, scripts/aws/cfn/microservice.yml
Alarm on SenderDashboardDataIndexer Lambda if lastDate is less than `today - N` days, where `N` is a configuration parameter of the Lambda function.
Also handled the FakeRole of DataLake for hotfix environment.
- Add DataIndexerLambdaAlarmNDays parameter
- Add function to check the dates
=> PN-12092 - Alarm on SenderDashboardDataIndexer lambda

docs/openapi/info-pa-schemas/info-pa.yaml, docs/openapi/info-recipient-schemas/info-recipient.yaml, docs/openapi/payments-schemas/payments.yaml, pom.xml, src/main/java/it/pagopa/pn/bff/pnclient/externalregistries/PnExternalRegistriesClientImpl.java, src/test/java/it/pagopa/pn/bff/pnclient/externalregistries/PnExternalRegistriesClientImplTest.java, src/test/java/it/pagopa/pn/bff/pnclient/externalregistries/PnExternalRegistriesClientImplTestIT.java
To manage the case of more than 100 institutions, we have migrated to user-institutions api.
- Updated commitId of ext-registry
- Updated api called for getting pa institutions
- Updated test
Test the api with postman. we don't have a pa with more than 100 institutions, so check only if the response is the same as before.
=> migrated to new api user-institutions - pn-12256

scripts/aws/cfn/microservice-dev-cfg.json
Remove /public prefix in WebLandingBucketPrefix env
- Remove /public prefix in WebLandingBucketPrefix env
=> [PN-12623] Remove /public prefix in WebLandingBucketPrefix env

docs/openapi/notification-schemas/notification.yaml, docs/openapi/notification-schemas/parameters-notification.yaml, docs/openapi/payments-schemas/payments.yaml, pom.xml, src/main/java/it/pagopa/pn/bff/mappers/notifications/NotificationSentDetailMapper.java, src/main/java/it/pagopa/pn/bff/mappers/notifications/SenderNotificationTimelineMapper.java, src/main/java/it/pagopa/pn/bff/pnclient/delivery/PnDeliveryClientPAImpl.java, src/main/java/it/pagopa/pn/bff/service/NotificationsPAService.java, src/test/java/it/pagopa/pn/bff/mappers/notifications/NotificationSentDetailMapperTest.java, src/test/java/it/pagopa/pn/bff/mocks/NotificationDetailPaMock.java, src/test/java/it/pagopa/pn/bff/pnclient/delivery/PnDeliveryClientPAImplTest.java, src/test/java/it/pagopa/pn/bff/pnclient/delivery/PnDeliveryClientPAImplTestIT.java, src/test/java/it/pagopa/pn/bff/utils/NotificationDetailUtilityTest.java
Migrated to version 2.4 for the sender notificaion detail api
- Updated pom
- Updated openapi file
- Updated PA client, service, controller and mapper
Start the bff -> open postman and check that the api works well
=> migrated to v2.4 for sender notification detail - pn-12709

docs/openapi/api-external-pn-bff-tos-privacy.yaml, docs/openapi/api-internal-pn-bff-tos-privacy.yaml, docs/openapi/aws/api-bff-WEB-aws.yaml, src/main/java/it/pagopa/pn/bff/rest/TosPrivacyController.java
Renamed operation id for get pg tos acceptance api
- Updated api-internal-pn-bff-tos-privacy.yaml
Run maven clean install -> check that everything is ok -> run tests -> check that everything is ok
=> renamed get pg tos acceptance api

functions/senderDashboardDataIndexer/package-lock.json, functions/senderDashboardDataIndexer/package.json
Removed useless dependencies from senderDashboardDataIndexer package.json
- Updated package.json
Go to functions/senderDashboardDataIndexer, run tests and check that everything is ok
=> removed useless dependencies

docs/openapi/apikeys-schemas/api-keys.yaml, docs/openapi/apikeys-schemas/public-keys.yaml, docs/openapi/apikeys-schemas/virtual-keys.yaml, docs/openapi/digital-addresses-schemas/digital-addresses.yaml, docs/openapi/downtime-logs-schemas/downtime-logs.yaml, docs/openapi/info-pa-schemas/info-pa.yaml, docs/openapi/info-recipient-schemas/info-recipient.yaml, docs/openapi/mandate-schemas/mandate.yaml, docs/openapi/notification-schemas/notification.yaml, docs/openapi/notification-schemas/parameters-notification.yaml, docs/openapi/payments-schemas/payments.yaml, docs/openapi/tos-privacy-schemas/tos-privacy.yaml, pom.xml
Updated micro services dependencies in the pom and in the openapi files
- Updated pom
- Updated openapi files
Run clean install -> run tests -> check that everything is ok
=> updated micro services dependencies

scripts/aws/cfn/microservice-dev-cfg.json, scripts/aws/cfn/microservice.yml, src/main/java/it/pagopa/pn/bff/config/MsClientConfig.java, src/main/resources/application.properties
Disable retry attempts on API
- Added the property `pn.bff.retry.max-attempts` and set it to 0
- Overridden the default max-attempts property with the one mentioned above
=> PN-12858 - Disable retry attempts

src/main/java/it/pagopa/pn/bff/utils/NotificationDetailUtility.java
insert new allowed code in analog flow
=> insert new allowed code in analog flow

pom.xml
=> increment minor version

docs/openapi/notification-schemas/notification.yaml, docs/openapi/notification-schemas/parameters-notification.yaml, pom.xml
Add `NOTIFICATION_CANCELLED` to `LegalFactCategory`
- Add `NOTIFICATION_CANCELLED` to `LegalFactCategory`
- Removed useless `BffQueryDocumentCategory`
- Update commitId of `pn-delivery-push`
Run `mvn clean compile` and `mvn test` and check that everything is ok
=> PN-13031 - Add `NOTIFICATION_CANCELLED` to `LegalFactCategory`

.github/workflows/actions/update-dependencies/action.yml, .github/workflows/actions/update-dependencies/src/file-helper.js, .github/workflows/actions/update-dependencies/src/repository-helper.js, .github/workflows/update-microservices-dependencies.yml
Fix action github used to update ms dependencies
Merge this pr and run the action
=> Fix github action - pn-11377

pom.xml
=> [1.5.0] Version 1.5.0

pom.xml
=> [1.6.0] Version 1.6.0

scripts/aws/cfn/microservice-dev-cfg.json
=> PN-13714: disable spring analizer

docs/openapi/aws/api-bff-WEB-aws.yaml, pom.xml
Update codegen for dynamic header `x-pagopa-pn-src-ch`
=> sourceChannel header: update codegen

docs/openapi/api-internal-pn-bff-recipient-notifications.yaml, docs/openapi/notification-schemas/notification.yaml, docs/openapi/notification-schemas/parameters-notification.yaml, docs/openapi/payments-schemas/payments.yaml, pom.xml, src/main/java/it/pagopa/pn/bff/pnclient/delivery/PnDeliveryClientRecipientImpl.java, src/main/java/it/pagopa/pn/bff/rest/ReceivedNotificationController.java, src/main/java/it/pagopa/pn/bff/service/NotificationsRecipientService.java, src/test/java/it/pagopa/pn/bff/mocks/NotificationsReceivedMock.java, src/test/java/it/pagopa/pn/bff/pnclient/delivery/PnDeliveryClientRecipientImplTest.java, src/test/java/it/pagopa/pn/bff/pnclient/delivery/PnDeliveryClientRecipientImplTestIT.java, src/test/java/it/pagopa/pn/bff/rest/ReceivedNotificationControllerTest.java, src/test/java/it/pagopa/pn/bff/service/NotificationRecipientServiceTest.java, src/test/java/it/pagopa/pn/bff/utils/PnBffRestConstants.java
Update `pn-delivery` client. Some API now require source header 
Check these api:
- GET /bff/v1/notifications/received/{iun}
- GET /bff/v1/notifications/received/{iun}/documents/{documentType}
- GET /bff/v1/notifications/received/{iun}/payments/{attachmentName}
=> feat/PN-14006: update delivery client

docs/openapi/aws/api-bff-WEB-aws.yaml, pom.xml
- Feature A
- Feature B
Run all test suite. Go to web portals and check that everything is ok
=> PN-13995: pom update with codegen version - regenerate openapi for aws

scripts/aws/cfn/microservice.yml
Changes microservice.yml to update  secrets/parameters layer ARN to v.17
- microservice.yml
=> chore(PN-14429): update secrets/parameters layer ARN from version 11 to 17

functions/raddStoreRegistryLambda/.prettierrc, functions/raddStoreRegistryLambda/event.json, functions/raddStoreRegistryLambda/index.js, functions/raddStoreRegistryLambda/package-lock.json, functions/raddStoreRegistryLambda/package.json, functions/raddStoreRegistryLambda/sonarqube-scanner.js, functions/raddStoreRegistryLambda/src/app/StoreLocatorCsvEntity.js, functions/raddStoreRegistryLambda/src/app/csvUtils.js, functions/raddStoreRegistryLambda/src/app/eventHandler.js, functions/raddStoreRegistryLambda/src/app/raddClient.js, functions/raddStoreRegistryLambda/src/app/s3Utils.js, functions/raddStoreRegistryLambda/src/app/ssmParameter.js, functions/raddStoreRegistryLambda/src/app/utils.js, functions/raddStoreRegistryLambda/src/test/StoreLocatorCsvEntity.test.js, functions/raddStoreRegistryLambda/src/test/csvUtils.test.js, functions/raddStoreRegistryLambda/src/test/eventHandler.test.js, functions/raddStoreRegistryLambda/src/test/raddClient.test.js, functions/raddStoreRegistryLambda/src/test/s3Utils.test.js, functions/raddStoreRegistryLambda/src/test/ssmParameter.test.js, functions/raddStoreRegistryLambda/src/test/utils.test.js
Add `prettier` as `devDependency` and run an `npm run format` command to format all files inside `raddStoreRegistry` Lambda
- Add prettier dependency and prettier command
=> chore: add prettier and format code on `raddStoreRegistryLambda`
